name: CI

permissions:
  contents: read
  actions: read
  pull-requests: write
  security-events: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    if: github.run_id != 1
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/build-dotnet-single.yml@b26c32ca0788a3a0fb22c2cfe5f8be0ccde46a1b # 2.5.130
    with:
      dotnetLogging: ${{ inputs.dotnet-logging }}
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      solution: ###SOLUTION###
    secrets: inherit
