name: Update template files

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  template-sync:
    if: github.repository == 'dailydevops/template-dotnet'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ahmadnassri/action-template-repository-sync@914d71f2dd5397ca50f1271001c560a5aca03436 # v2.6.14
        with:
          github-token: ${{ secrets.TEMPLATE_SYNC }}
          dry-run: false
          skip-ci: true
