name: Update template files

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  template-sync:
    if: github.repository == 'dailydevops/template-dotnet'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: ahmadnassri/action-template-repository-sync@914d71f2dd5397ca50f1271001c560a5aca03436 # v2.6.14
        with:
          github-token: ${{ secrets.TEMPLATE_SYNC }}
          dry-run: false
          skip-ci: true
