name: Update template files

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  template-sync:
    if: github.repository == 'dailydevops/template-dotnet'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ahmadnassri/action-template-repository-sync@233c84219c88745aa5024ca2b4d248edf85c10d5 # v2.6.13
        with:
          github-token: ${{ secrets.TEMPLATE_SYNC }}
          dry-run: false
          skip-ci: true
